import mermaid from "mermaid";
import { basicSetup, EditorView } from "codemirror";
import { EditorState } from "@codemirror/state";
import { keymap } from "@codemirror/view";
import { javascript } from "@codemirror/lang-javascript";
import { oneDark } from "@codemirror/theme-one-dark";

type TreeNode={name:string;path:string;kind:"directory"|"file";children?:TreeNode[];editable?:boolean};
type Diagram={kind:"packages"|"uml";scopePath:string;version:number;status:"ready"|"error";dsl:string;error?:string};
type FileResponse={path:string;content:string;hash:string;editable:boolean};
type WatchMessage={type:"changed";version:number;paths:string[];events:string[]}|{type:"watch-error";version:number;error:string};
const $=<T extends Element = HTMLInputElement>(selector:string)=>document.querySelector<T>(selector)!;
const state={tree:null as TreeNode|null,mode:"packages" as "packages"|"uml",scope:"",version:0,file:null as FileResponse|null,view:null as EditorView|null,dirty:false,conflict:false,ws:null as WebSocket|null,retry:250};
const viewport={scale:1,x:0,y:0,drag:false,px:0,py:0,apply(){ $("#svg-holder").style.transform=`translate(${this.x}px,${this.y}px) scale(${this.scale})`; },reset(){this.scale=1;this.x=0;this.y=0;this.apply();},zoom(delta:number){this.scale=Math.max(.2,Math.min(4,this.scale+delta));this.apply();}};
mermaid.initialize({startOnLoad:false,securityLevel:"strict",theme:"dark"});
async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,init);const body=await response.json() as T & {error?:string};if(!response.ok)throw new Error(body.error??`Request failed (${response.status})`);return body;}
function setStatus(text:string,error=false){const node=$("#status");node.textContent=text;node.classList.toggle("error",error);}
function showError(error:string|undefined){const panel=$("#error-panel");panel.textContent=error??"";panel.hidden=!error;}
function renderTree(){const root=$("#tree");root.replaceChildren();if(!state.tree)return;const filter=$("#tree-filter").value.toLowerCase();const draw=(node:TreeNode):HTMLElement|null=>{const matching=!filter||node.name.toLowerCase().includes(filter)||node.path.toLowerCase().includes(filter);const children=(node.children??[]).map(draw).filter((x):x is HTMLElement=>x!==null);if(!matching&&!children.length)return null;const wrap=document.createElement("div");const button=document.createElement("button");button.className=`tree-row ${state.scope===node.path&&state.mode===(node.kind==="file"?state.mode:"uml")?"selected":""}`;button.innerHTML=`<span class="icon">${node.kind==="directory"?"▸":"·"}</span><span>${node.name}</span>`;button.onclick=()=>node.kind==="directory"?selectScope(node):openFile(node.path);wrap.append(button);if(children.length){const nested=document.createElement("div");nested.className="tree-children";children.forEach((child)=>nested.append(child));wrap.append(nested);}return wrap;};const result=draw(state.tree);if(result)root.append(result);}
async function loadTree(){const response=await api<{version:number;root:TreeNode}>("/api/tree");state.tree=response.root;state.version=response.version;$("#source-label").textContent=response.root.name;renderTree();}
async function loadDiagram(){const query=new URLSearchParams({kind:state.mode,path:state.scope});const diagram=await api<Diagram>(`/api/diagram?${query}`);state.version=diagram.version;$("#dsl-content").textContent=diagram.dsl;showError(diagram.status==="error"?diagram.error:undefined);try{const rendered=await mermaid.render(`diagram-${Date.now()}`,diagram.dsl);$("#svg-holder").innerHTML=rendered.svg;viewport.apply();setStatus(diagram.status==="error"?"Diagram parse error":`Updated · v${diagram.version}`,diagram.status==="error");}catch(error){showError(error instanceof Error?error.message:String(error));setStatus("Mermaid render error",true);}}
async function selectScope(node:TreeNode){state.mode=node.path===""||node.name==="packages"?"packages":"uml";state.scope=node.path;document.querySelectorAll(".mode").forEach((button)=>button.classList.toggle("active",button.id===`${state.mode}-mode`));viewport.reset();renderTree();try{await loadDiagram();}catch(error){showError(error instanceof Error?error.message:String(error));setStatus("Request failed",true);}}
function destroyEditor(){state.view?.destroy();state.view=null;state.file=null;state.dirty=false;$("#editor-panel").hidden=true;$("#conflict").hidden=true;}
async function openFile(path:string){try{const file=await api<FileResponse>(`/api/file?path=${encodeURIComponent(path)}`);destroyEditor();state.file=file;$("#editor-panel").hidden=false;$("#editor-name").textContent=path.split("/").at(-1)??path;$("#editor-path").textContent=path;const extensions=[basicSetup,javascript({typescript:true,jsx:path.endsWith(".tsx")}),oneDark,keymap.of([{key:"Mod-s",run:()=>{void saveFile();return true;}}]),EditorView.updateListener.of((update)=>{if(update.docChanged){state.dirty=true;}})];if(!file.editable)extensions.push(EditorState.readOnly.of(true),EditorView.editable.of(false));state.view=new EditorView({state:EditorState.create({doc:file.content,extensions}),parent:$("#editor")});setStatus(file.editable?"Editing source":"Read-only file");}catch(error){setStatus(error instanceof Error?error.message:String(error),true);}}
async function formatFile(){if(!state.file||!state.view)return;try{const response=await api<{path:string;content:string}>("/api/file/format",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({path:state.file.path,content:state.view.state.doc.toString()})});state.view.dispatch({changes:{from:0,to:state.view.state.doc.length,insert:response.content}});setStatus("Formatted in memory");}catch(error){setStatus(error instanceof Error?error.message:String(error),true);}}
async function saveFile(){if(!state.file?.editable||!state.view)return;try{const saved=await api<FileResponse>("/api/file",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({path:state.file.path,content:state.view.state.doc.toString(),baseHash:state.file.hash})});state.file=saved;state.dirty=false;state.conflict=false;$("#conflict").hidden=true;setStatus("Saved to disk");}catch(error){setStatus(error instanceof Error?error.message:String(error),true);}}
async function reloadOpenFile(){if(!state.file)return;const path=state.file.path;const wasDirty=state.dirty;destroyEditor();await openFile(path);if(wasDirty)setStatus("Reloaded disk version");}
function handleWatch(message:WatchMessage){if(message.type==="watch-error"){setStatus(message.error,true);return;}state.version=message.version;const openPath=state.file?.path;if(openPath&&message.paths.includes(openPath)&&state.dirty){state.conflict=true;$("#conflict").hidden=false;}else if(openPath&&message.paths.includes(openPath)){void reloadOpenFile();}void loadTree();void loadDiagram();setStatus(`Source changed · v${message.version}`);}
function connect(){const protocol=location.protocol==="https:"?"wss":"ws";const ws=new WebSocket(`${protocol}://${location.host}/ws`);state.ws=ws;ws.onopen=()=>{state.retry=250;setStatus("Watcher connected");};ws.onmessage=(event)=>{try{handleWatch(JSON.parse(event.data) as WatchMessage);}catch(error){setStatus(String(error),true);}};ws.onclose=()=>{setStatus("watcher disconnected",true);setTimeout(connect,state.retry);state.retry=Math.min(2000,state.retry*2);};}
$("#packages-mode").onclick=()=>void selectScope({name:"Packages",path:"",kind:"directory"});$("#uml-mode").onclick=()=>{if(state.scope)void selectScope({name:"Selected",path:state.scope,kind:"directory"});};$("#tree-filter").oninput=renderTree;$("#zoom-in").onclick=()=>viewport.zoom(.2);$("#zoom-out").onclick=()=>viewport.zoom(-.2);$("#zoom-reset").onclick=()=>viewport.reset();$("#legend-toggle").onclick=()=>{$("#legend").hidden=!$("#legend").hidden;};$("#sidebar-toggle").onclick=()=>$("#sidebar").classList.toggle("collapsed");$("#editor-close").onclick=destroyEditor;$("#format-file").onclick=()=>void formatFile();$("#save-file").onclick=()=>void saveFile();$("#reload-file").onclick=()=>void reloadOpenFile();$("#keep-file").onclick=()=>{state.conflict=false;$("#conflict").hidden=true;setStatus("Keeping browser buffer");};
$("#diagram-stage").addEventListener("wheel",(event)=>{event.preventDefault();viewport.zoom(event.deltaY>0?-.1:.1);},{passive:false});$("#diagram-stage").addEventListener("pointerdown",(event)=>{viewport.drag=true;viewport.px=event.clientX;viewport.py=event.clientY;$("#diagram-stage").classList.add("dragging");});window.addEventListener("pointermove",(event)=>{if(!viewport.drag)return;viewport.x+=event.clientX-viewport.px;viewport.y+=event.clientY-viewport.py;viewport.px=event.clientX;viewport.py=event.clientY;viewport.apply();});window.addEventListener("pointerup",()=>{viewport.drag=false;$("#diagram-stage").classList.remove("dragging");});
await loadTree();await loadDiagram();connect();
